# Generated by Django 4.2.7 on 2023-11-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Staff_Id',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
