# Generated by Django 4.2.7 on 2023-11-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Staff_Id',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type_of_staff',
            field=models.CharField(choices=[('Teaching', 'Teaching staff'), ('Non-teaching', 'Non Teaching staff')], default='Teaching', max_length=30),
        ),
    ]
