# Generated by Django 4.2.7 on 2023-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_staff_id_staff_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
