# Generated by Django 4.2.7 on 2023-11-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='type_of_staff',
        ),
    ]
