# Generated by Django 4.2.7 on 2023-11-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staff_type_of_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type_of_staff',
            field=models.CharField(choices=[('AT', 'Teaching staff'), ('ANT', 'Non Teaching staff')], default='AT', max_length=30),
        ),
    ]
