# Generated by Django 4.2.7 on 2023-11-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_type_of_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='type_of_staff',
            field=models.CharField(choices=[('Teaching', 'Teaching staff'), ('Non-teaching', 'Non Teaching staff')], default='Teaching', max_length=30),
        ),
    ]
