# Generated by Django 4.2.7 on 2023-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
