# Generated by Django 4.2.7 on 2023-11-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_name'),
        ('student', '0003_rename_student_id_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='department.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
